[package]
name = "kendall_py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "kendall_py"
crate-type = ["cdylib"]

[dependencies]
kendall = { path = "../kendall" }
pyo3 = "0.22.0"
